[package]
name = "embed-constvec"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "Inline fixed capacity vec/array"
categories = ["data-structures", "no-std"]
homepage = "https://github.com/NaturalIO/embed-collections-rs"
readme = "../README.md"

[dependencies]

[dev-dependencies]
embed-collections-test = {path="../test-common"}

[package.metadata.docs.rs]
all-features = true
# enable features in the documentation
rustdoc-args = ["--cfg", "docsrs"]

[lints]
workspace = true
