[package]
name = "embed-dlist"
version = "0.3.0"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "intrusive doubly linkedlist"
keywords = ["linked-list", "intrusive"]
categories = ["data-structures", "no-std"]
homepage = "https://github.com/NaturalIO/embed-collections-rs"
readme = "../README.md"

[dependencies]
pointers = {version="0"}

[dev-dependencies]
log = { version="0"}

[features]
default = []
std = []

[package.metadata.docs.rs]
all-features = true
# enable features in the documentation
rustdoc-args = ["--cfg", "docsrs"]

[lints]
workspace = true
